import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  PIN_TAG,
  escapeMdHtml,
  toStarlightPage,
  checkProvenance,
  syncToolDocs,
} from '../scripts/sync-tool-docs.mjs';

const TOOLS_JSON = JSON.stringify({
  provenance: { package_version: '0.1.0', git_describe: '2606-3-gabc', source_sha: 'abc' },
  tools: [{ name: 'ros2_topic_list', description: 'x', input_schema: {}, mutating: false }],
});
const TOOLS_MD = `---
title: Tool reference
description: Every tool.
---

<!-- GENERATED by scripts/gen_tool_docs.py. Do not edit by hand. -->

| Tool | Summary |
| --- | --- |
| \`ros2_action_subscribe_status\` | Subscribe to '/<action>/_action/status' and \`/<a>/b\` |

<details><summary>Input schema (JSON)</summary>

\`\`\`json
{ "a": "<b>" }
\`\`\`

</details>
`;

function fakeFetch({ latest = '2610', fail = false, status = 200 } = {}) {
  const calls = [];
  const fn = async (url) => {
    calls.push(url);
    if (fail) throw new Error('network down');
    if (url.includes('/releases/latest')) return { ok: status === 200, status, json: async () => ({ tag_name: latest }) };
    if (url.includes('/commits/')) return { ok: true, status: 200, json: async () => ({ sha: 'deadbeef' }) };
    if (url.endsWith('tools.json')) return { ok: true, status: 200, text: async () => TOOLS_JSON };
    if (url.endsWith('tools.md')) return { ok: true, status: 200, text: async () => TOOLS_MD };
    return { ok: false, status: 404, text: async () => '' };
  };
  fn.calls = calls;
  return fn;
}

let dir;
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'tooldocs-'));
});
afterEach(() => rmSync(dir, { recursive: true, force: true }));

const paths = () => ({ cacheDir: join(dir, 'cache'), pagePath: join(dir, 'page', 'tools.md') });

describe('escapeMdHtml', () => {
  it('escapes stray angle brackets in prose but keeps code, comments and details/summary', () => {
    const out = escapeMdHtml(TOOLS_MD);
    expect(out).toContain("'/&lt;action>/_action/status'");
    expect(out).toContain('`/<a>/b`');
    expect(out).toContain('{ "a": "<b>" }');
    expect(out).toContain('<details><summary>Input schema (JSON)</summary>');
    expect(out).toContain('</details>');
    expect(out).toContain('<!-- GENERATED');
  });
});

describe('toStarlightPage', () => {
  it('adds provenance to the frontmatter and a visible pinned-release line', () => {
    const page = toStarlightPage(TOOLS_MD, { tag: '2610', sha: 'deadbeef' });
    expect(page.startsWith('---\ntitle: Tool reference\n')).toBe(true);
    expect(page).toContain('editUrl: false');
    expect(page).toContain('toolDocsTag: "2610"');
    expect(page).toMatch(/Pinned to ROS2 MCP release \[`2610`\]\(https:\/\/github.com\/wise-vision\/ros2_mcp\/releases\/tag\/2610\)/);
    expect(page).not.toContain('<!-- GENERATED');
  });
  it('rejects input without frontmatter', () => {
    expect(() => toStarlightPage('# no frontmatter', { tag: '1', sha: 'x' })).toThrow(/frontmatter/);
  });
});

describe('checkProvenance', () => {
  it('passes when the pinned tag is the latest release', () => {
    expect(() => checkProvenance('2610', '2610')).not.toThrow();
  });
  it('fails when the pin lags the latest release', () => {
    expect(() => checkProvenance('2610', '2701')).toThrow(/2610.*2701/);
  });
});

describe('syncToolDocs', () => {
  it('pins 2610', () => expect(PIN_TAG).toBe('2610'));

  it('fetches the pinned tag, writes the page and refreshes the cache', async () => {
    const fetch = fakeFetch();
    const r = await syncToolDocs({ ...paths(), fetch, env: {}, log: () => {} });
    expect(r.source).toBe('network');
    expect(fetch.calls.some((u) => u.includes('/wise-vision/ros2_mcp/2610/docs/generated/tools.md'))).toBe(true);
    const page = readFileSync(paths().pagePath, 'utf8');
    expect(page).toContain('toolDocsSha: "deadbeef"');
    const prov = JSON.parse(readFileSync(join(paths().cacheDir, 'provenance.json'), 'utf8'));
    expect(prov).toMatchObject({ tag: '2610', sha: 'deadbeef', latest_release: '2610' });
    expect(existsSync(join(paths().cacheDir, 'tools.json'))).toBe(true);
  });

  it('FAILS when the pinned tag is not the latest release (even with a cache)', async () => {
    await syncToolDocs({ ...paths(), fetch: fakeFetch(), env: {}, log: () => {} });
    await expect(
      syncToolDocs({ ...paths(), fetch: fakeFetch({ latest: '2701' }), env: {}, log: () => {} }),
    ).rejects.toThrow(/not the latest release/);
  });

  it('offline: falls back to the committed cache locally, loudly', async () => {
    await syncToolDocs({ ...paths(), fetch: fakeFetch(), env: {}, log: () => {} });
    rmSync(paths().pagePath);
    const logs = [];
    const r = await syncToolDocs({ ...paths(), fetch: fakeFetch({ fail: true }), env: {}, log: (m) => logs.push(m) });
    expect(r.source).toBe('cache');
    expect(logs.join('\n')).toMatch(/OFFLINE/);
    expect(readFileSync(paths().pagePath, 'utf8')).toContain('toolDocsTag: "2610"');
  });

  it('offline in CI: fails loudly instead of using the cache', async () => {
    await syncToolDocs({ ...paths(), fetch: fakeFetch(), env: {}, log: () => {} });
    await expect(
      syncToolDocs({ ...paths(), fetch: fakeFetch({ fail: true }), env: { CI: 'true' }, log: () => {} }),
    ).rejects.toThrow(/CI.*cannot reach/);
  });

  it('offline with a cache from a different tag: fails', async () => {
    mkdirSync(paths().cacheDir, { recursive: true });
    writeFileSync(join(paths().cacheDir, 'provenance.json'), JSON.stringify({ tag: '2606' }));
    writeFileSync(join(paths().cacheDir, 'tools.md'), TOOLS_MD);
    await expect(
      syncToolDocs({ ...paths(), fetch: fakeFetch({ fail: true }), env: {}, log: () => {} }),
    ).rejects.toThrow(/cache is for 2606/);
  });

  it('offline with no cache: fails', async () => {
    await expect(
      syncToolDocs({ ...paths(), fetch: fakeFetch({ fail: true }), env: {}, log: () => {} }),
    ).rejects.toThrow(/no cache/);
  });

  it('GitHub API error status is treated as unreachable', async () => {
    await expect(
      syncToolDocs({ ...paths(), fetch: fakeFetch({ status: 403 }), env: { CI: '1' }, log: () => {} }),
    ).rejects.toThrow(/cannot reach/);
  });

  it('sends the GitHub token when present', async () => {
    const seen = [];
    const base = fakeFetch();
    const fetch = async (url, init) => {
      seen.push(init?.headers?.authorization);
      return base(url, init);
    };
    await syncToolDocs({ ...paths(), fetch, env: { GITHUB_TOKEN: 't0k' }, log: () => {} });
    expect(seen).toContain('Bearer t0k');
  });
});
