#!/usr/bin/env node
// Generates src/styles/tokens.css + src/styles/tokens.json from src/styles/tokens.source.json.
// The CSS is imported by the site AND by HyperFrames templates; the JSON serves JS consumers (three.js hero).
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const META = new Set(['pairs']);

export function flatten(obj, prefix = []) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$') || META.has(k)) continue;
    const path = k === 'DEFAULT' ? prefix : [...prefix, k];
    if (v && typeof v === 'object' && !Array.isArray(v)) Object.assign(out, flatten(v, path));
    else out[path.join('-')] = String(v);
  }
  return out;
}

const HEADER = '/* GENERATED by scripts/build-tokens.mjs from tokens.source.json. Do not edit by hand. */\n';

export function toCss(src) {
  const lines = Object.entries(flatten(src)).map(([k, v]) => `  --${k}: ${v};`);
  return `${HEADER}:root {\n${lines.join('\n')}\n}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-duration-fast: 0ms;\n    --motion-duration-base: 0ms;\n    --motion-duration-reveal: 0ms;\n    --motion-distance-reveal: 0px;\n  }\n}\n`;
}

export function toJson(src) {
  const { $description, ...rest } = src;
  return JSON.stringify({ $generated: 'scripts/build-tokens.mjs', ...rest, flat: flatten(src) }, null, 2) + '\n';
}

export function buildTokens(src) {
  return { css: toCss(src), json: toJson(src) };
}

/* c8 ignore start */
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dir = resolve(fileURLToPath(new URL('../src/styles/', import.meta.url)));
  const src = JSON.parse(readFileSync(resolve(dir, 'tokens.source.json'), 'utf8'));
  const { css, json } = buildTokens(src);
  writeFileSync(resolve(dir, 'tokens.css'), css);
  writeFileSync(resolve(dir, 'tokens.json'), json);
  console.log('tokens: wrote src/styles/tokens.css + tokens.json');
}
/* c8 ignore stop */
